---
- name: create esalas
  ansible.builtin.user:
    name: esalas
    shell: /bin/bash
- name: passwordless sudo for esalas
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/esalas
    state: present
    create: yes
    regexp: "^esalas"
    line: "esalas ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: remove sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^esalas"
    line: "esalas ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
- name: create esalas .ssh directory
  ansible.builtin.file:
    path: /home/esalas/.ssh
    mode: '0700'
    owner: esalas
    state: directory
- name: grab authorized_keys file
  ansible.builtin.copy:
    src: esalas/authorized_keys
    dest: /home/esalas/.ssh/authorized_keys
    mode: '0600'
    owner: esalas


