---
- name: create patrick
  ansible.builtin.user:
    name: patrick
    shell: /bin/bash
- name: passwordless sudo for patrick
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/patrick
    state: present
    create: yes
    regexp: "^patrick"
    line: "patrick ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: remove sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^patrick"
    line: "patrick ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
- name: create patrick .ssh directory
  ansible.builtin.file:
    path: /home/patrick/.ssh
    mode: '0700'
    owner: patrick
    state: directory
- name: grab authorized_keys file
  ansible.builtin.copy:
    src: patrick/authorized_keys
    dest: /home/patrick/.ssh/authorized_keys
    mode: '0600'
    owner: patrick
- name: disable password aging
  ansible.builtin.shell: 'chage -I -1 -m 0 -M 99999 -E -1 patrick'
