---
- name: create cron to keep state in sync
  ansible.builtin.cron:
    name: ansible-pull
    minute: 0
    job: ANSIBLE_LOG_PATH="/var/log/ansible.log" ansible-pull -U https://github.com/GraywellDesign/ansible playbooks/servers/server.yml 2>&1 1>/dev/null
- name: check if jcagent is installed
  ansible.builtin.shell: dpkg -l | grep jcagent
  register: jcagent_installed
  ignore_errors: True
  check_mode: False
  changed_when: False
- name: stop jumpcloud service
  ansible.builtin.systemd:
    name: jcagent.service
    state: stopped
  when: jcagent_installed.rc == 0
- name: uninstall jumpcloud agent
  ansible.builtin.command:
    name: jcagent
    state: absent
  when: jcagent_installed.rc == 0
- name: remove jcagent directory
  ansible.builtin.file:
    path: /opt/jc
    state: absent
  when: jcagent_installed.rc == 0
