---
- name: create cron to keep state in sync
  ansible.builtin.cron:
    name: ansible-pull
    minute: 0
    job: ANSIBLE_LOG_PATH="/var/log/ansible.log" ansible-pull -U https://github.com/GraywellDesign/ansible playbooks/servers/server.yml 2>&1 1>/dev/null
- name: check installed packages
  package_facts:
    manager: "auto"
- name: stop jumpcloud service
  ansible.builtin.systemd:
    name: jcagent.service
    state: stopped
  when: "'jcagent' in ansible_facts.packages"
- name: uninstall jumpcloud agent
  ansible.builtin.apt:
    name: jcagent
    state: absent
  when: "'jcagent' in ansible_facts.packages"
- name: remove jcagent directory
  ansible.builtin.file:
    path: /opt/jc
    state: absent
  when: "'jcagent' in ansible_facts.packages"
- name: stop auditbeat, metricbeat, packetbeat, launcher
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
  - auditbeat.service
  - metricbeat.service
  - packetbeat.service
  - launcher.service
  ignore_errors: yes
- name: remove debsecan cron
  ansible.builtin.cron:
    name: daily debsecan cronjob
    state: absent
- name: remove rkhunter cron
  ansible.builtin.cron:
    name: rkhunter daily cron
    state: absent
- name: import mysql gpg key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 467B942D3A79BD29
